events {
    worker_connections 1024;
}

http {
    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server backend:8080;
    }

    # permanent redirect to https
    server {
        listen 80;
        listen [::]:80;
        rewrite ^ https://$host$request_uri? permanent;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        http2  on;

        server_name localhost;

        ssl_certificate /etc/nginx/certs/development.crt;
        ssl_certificate_key /etc/nginx/certs/development.key;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/errors.log;

        # Frontend
        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cache_bypass $http_upgrade;

            error_log /var/log/nginx/frontend_errors.log;
        }

        # Backend API
        location /api {
            # Remove /api prefix when passing to backend
            rewrite ^/api(/.*)$ $1 break;

            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Important for websockets if you use them
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Timeout settings
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            send_timeout 300s;

            # access_log /var/log/nginx/backend_api_access.log;
            error_log /var/log/nginx/backend_api_errors.log;
        }

        # Backend Page
        location /page {
            # Remove /page prefix when passing to backend
            rewrite ^/(/.*)$ $1 break;

            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # access_log /var/log/nginx/backend_page_access.log;
            error_log /var/log/nginx/backend_page_errors.log;
        }
    }
}