server {
    listen 80;
    server_name localhost;
    listen [::]:80 default_server;
    # listen 443 ssl;
    # listen [::]:443 ssl;

    # Serve React frontend static files
    location / {
        # root /usr/share/nginx/html
        root /app/dist;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;  # Handle React Router
        
        # try_files $uri $uri/ =404;
        proxy_pass          http://frontend:3000/;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        # proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header    X-Forwarded-Proto $scheme;
        # proxy_read_timeout  90;
    }

    # Proxy API requests to Gin backend
    location /api {
        rewrite             /api/(.*) /$1 break;
        proxy_pass          http://api:8080;
        proxy_redirect      off;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        
        # CORS
        add_header "Access-Control-Allow-Origin" "*" always;
        add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, DELETE, PUT" always;
        add_header "Access-Control-Allow-Credentials" "true" always;
        add_header "Access-Control-Allow-Headers" "User-Agent,Keep-Alive,Content-Type,Authorization" always;
        
        if ($request_method = 'OPTIONS') {
            return 204;
        }

    }
}